name: CI-CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

  deploy:
    name: Deploy container
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Show deployment instructions
        run: |
          echo "=== CI/CD Pipeline Completed Successfully! ==="
          echo ""
          echo "Docker image has been built and pushed to Docker Hub:"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest"
          echo ""
          echo "To deploy manually on any machine:"
          echo "1. docker login -u '${{ secrets.DOCKER_USERNAME }}'"
          echo "2. docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest"
          echo "3. docker run -d --name cicd-demo -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest"
          echo ""
          echo "Your API will be available at: http://localhost/"
          echo "Health check: http://localhost/health"
